### ISSUE TITLE
(M1) Creacion de metodo 'desactivarUsuario()'

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/prjEstructurasG5#3]
Este medoto debera recibir por parametros: 
- [x] usuario

Buscar en la lista si alguno coincide, en caso de que encuentra desactivara al usuario, en caso contrario lanzara un mensaje de usuario no encontrado.

**Comment by Marcel1203** [comment]
posible solucion de desactivar usuario

**Comment by Marcel1203** [comment]
listo
